from os import times
import requests # we use this lib. in python to interact with API's 
from django.shortcuts import render, redirect
from django.db.models.expressions import result
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse # json format for our results as well queries 
from .models import Transactions
import base64 # encryption at a script one 
from datetime import datetime
import json
from django.core.mail import send_mail
from django.core.paginator import Paginator
import os
from dotenv import load_dotenv

load_dotenv() # making our settings config available to our view files 


# Create your views here.
# helper class for transaction security credentials  :: Auth token :: - access to use the API routes from daraja mpesa 
# authorization 
# password required by daraja api to authorize api(s) usage 
SHORTCODE = os.getenv('SHORTCODE')
PASSKEY = os.getenv('PASSKEY')
BASE_URL = os.getenv('BASE_URL')
CONSUMER_KEY = os.getenv('CONSUMER_KEY')
CONSUMER_SECRET = os.getenv('CONSUMER_SECRET')
NGROK_URL = os.getenv('NGROK_URL')
CALLBACK_URL = os.getenv('CALLBACK_URL')

class MpesaPassword:
    @staticmethod  # DECLARING THIS METHOD DOES NOT BELONG TO ANY OBJECT / OR CLASS 
    def generate_security_credential():
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        data_to_encode = SHORTCODE + PASSKEY + timestamp
        online_password = base64.b64encode(data_to_encode.encode()).decode()

        return online_password

# get the access token from mpesa 
# MPESA API - AUTHORIZATION TO GET AN ACCESS TOKEN 
def generate_access_token():
    auth_url = f'{BASE_URL}/oauth/v1/generate?grant_type=client_credentials' # endpoint 
    response = requests.get(auth_url, auth=(CONSUMER_KEY, CONSUMER_SECRET))
    return response.json().get('access_token')  # my access token from mpesa api 

# index page for transactions  # this gives back the checkout page 
def index(request):
    return render(request, 'mediampesa/index.html')

# this will execute an stk push on request 
# we exempt a csrf security check for external processes stk push / callback 
'''
1. Accept post data (phone , amount , name and email )
2. Create a pending transaction database 
3. Generate the access token 
4. generate of passwords + timestamp 
5. Sends the stk push request to safaricom via a daraja api endppoint 
6. Save a checkoutrequestid = id generated by saf. to id a particular transaction 
7. redirect users to a waiting page - stk push to input pin
'''
@csrf_exempt  
def stk_push(request):
    if request.method == 'POST':
        # simply capturing the form details 
        phone = request.POST.get('phone')
        amount = request.POST.get('amount')
        name = request.POST.get('name')
        email = request.POST.get('email')
        # we then create our intial transaction record in our db : SQL insert : ORM : objects.create 
        transaction = Transactions.objects.create(
            phone_number=phone,
            amount=amount,
            status="Pending",
            description="Awaiting status result",
            name=name,
            email=email,
        )
        # generate the access token for our user 
        access_token = generate_access_token()
        print("access token " , access_token)
        
        stk_url = f'{BASE_URL}/mpesa/stkpush/v1/processrequest'  # endpoint to initiate an stk push 
        # authorization headers to communicate to the endpoint 
        headers = {
            'Authorization': f'Bearer {access_token}',
            'Content-Type': 'application/json',
        }
        timestamp = datetime.now().strftime('%Y%m%d%H%M%S')
        password = base64.b64encode(f'{SHORTCODE}{PASSKEY}{timestamp}'.encode()).decode()
        print(stk_url)
        print(password)
        print(timestamp)

        payload = {
            "BusinessShortCode": SHORTCODE,
            "Password": password,
            "Timestamp": timestamp,
            "TransactionType": "CustomerPayBillOnline",
            "Amount": amount,
            "PartyA": phone,
            "PartyB": SHORTCODE,
            "PhoneNumber" : phone,
            "CallBackURL": f"{CALLBACK_URL}mediampesa/callback/", #  #- response from mpesa based on transaction success or failure  will be sent here 
            "AccountReference": f"Transaction_{transaction.id}",
            "TransactionDesc": "Payment for Services"
        }
        

        response = requests.post(stk_url, json=payload, headers=headers)
        print("response" , response)
        response_data = response.json() ## this is what I will consume on the users end 

        print(response_data)

        transaction_id = response_data.get('CheckoutRequestID', None) # identifies stk push was successfully launched 
        transaction.transaction_id = transaction_id
        transaction.description = response_data.get('ResponseDescription', "No Description")
        transaction.save()  ## save transaction to db : at this point for the transaction my user received the STK push i.e popup to enter mpesa pin to complete the pay.

        return redirect('mediampesa:waiting_page', transaction_id=transaction.id)

    return JsonResponse({'error': "invalid request"}, status=400)

# waiting page 
def waiting_page(request, transaction_id):
    transaction = Transactions.objects.get(id=transaction_id)
    return render(request, 'mediampesa/waiting.html',{'transaction_id': transaction_id}) # sharing the current executed transaction to my waiting page 

# this function maps my callback url that will receive the result body of a transaction/ payment attempt 
@csrf_exempt
def callback(request):
    if request.method == 'POST':
        try:
            # response from  daraja api upon payment attempt
            data = json.loads(request.body)
            print("received callback data " , data)
            stk_callback = data.get('Body',{}).get('stkCallback',{})
            result_code = stk_callback.get('ResultCode',None)
            result_desc = stk_callback.get('ResultDesc','')
            transaction_id = stk_callback.get('CheckoutRequestID',None)
            print(transaction_id,result_code)

            if transaction_id:
                transaction = Transactions.objects.filter(transaction_id=transaction_id).first()
                print("my transaction in db ", transaction)
                if transaction:
                    if result_code == 0: # 0 means success i.e. user was able to pay 
                        '''
                        [
                            {"value" : {
                                  "mpesaReceiptNumber" : uf34u983948394,
                                  "amount" : 48398493,
                                  "transactionDate" : "39449852025"
                                } }
                        ]
                        '''
                        callback_metadata = stk_callback.get('CallbackMetadata',{}).get('Item',[])
                        receipt_number = next((item.get('Value') for item in callback_metadata if item.get('Name') == 'MpesaReceiptNumber'), None)
                        amount = next((item.get('Value') for item in callback_metadata if item.get('Name') == 'Amount'), None)
                        transaction_date_str = next((item.get('Value') for item in callback_metadata if item.get('Name') == 'TransactionDate'), None)
                        # cleaning our transaction date screen
                        transaction_date = None
                        if transaction_date_str:
                            transaction_date = datetime.strptime(str(transaction_date_str), '%Y%m%d%H%M%S')

                        # updating transaction fields
                        transaction.mpesa_receipt_number = receipt_number
                        transaction.transaction_date = transaction_date
                        transaction.amount = amount
                        transaction.status = "Success"
                        transaction.description = "Payment Successful"
                        transaction.save()
                        print(f"Transaction {transaction_id} - {transaction.status} updated successfully")

                        ## TODO :  SEND EMAIL
                        if transaction.email:
                            subject = "Payment Receipt Confirmation"
                            message = (
                                f"Dear {transaction.name}, \n\n"
                                f"Thank you for your payment of {transaction.amount}"
                                f"Your MPESA confirmation receipt is {transaction.mpesa_receipt_number}"
                                "Best Regards , \n"
                                "STK PUSH"
                            )
                            html_message = (
                                f"<p>Dear {transaction.name},</p>"
                                f"<p>Thank you for your payment of {transaction.amount}</p>"
                                f"<p>Your MPESA confirmation receipt is {transaction.mpesa_receipt_number}</p>"
                                f"<p>Best Regards, STK Push</p>"
                            )
                            send_mail(subject,message,'josephbill00@gmail.com',[transaction.email]
                                      ,fail_silently=False,html_message=html_message,)
                            print("Payment receipt email sent successfully")

                    elif result_code == 1:
                        transaction.status = "Failed"
                        transaction.description = result_desc
                        transaction.save()
                        print(f"Transaction {transaction_id} - {result_desc} failed.")
                    elif result_code == 1032:
                        transaction.status = "Cancelled"
                        transaction.description = "Transaction Cancelled by User"
                        transaction.save()
                        print(f"Transaction {transaction_id} marked as cancelled.")

            return JsonResponse({"message": "callback received and processed"}, status=200)

        except Exception as e:
            print(f"Error processing callback {e}")
            return JsonResponse({"error": f"Error processing callback {e}"}, status=500)

    return JsonResponse({"error" : "Invalid request method"}, status=400)



def check_status(request, transaction_id):
    # get the transaction needed for the process
    transaction = Transactions.objects.filter(id=transaction_id).first()
    if not transaction:
        return JsonResponse({"status": "failed" , "message": "Transaction not found"}, status=400)

    '''
    on stk prompt the transaction status is pending 
    on successful payments the transaction status is success 
    on failure the transaction status is failed 
    on cancellation the transaction status is canceled
    '''

    if transaction.status == "Success":
        return JsonResponse({"status": "Success", "message": "Payment Successful"}, status=200)
    elif transaction.status == "Failed":
        return JsonResponse({"status": "Failed", "message": "Payment Failed"}, status=200)
    elif transaction.status == "Cancelled":
        return JsonResponse({"status": "Cancelled", "message": "Transaction was Cancelled"}, status=200)
    else:
        return JsonResponse({"status": "Pending", "message": "Transaction still being processed."}, status=400)


def payment_success(request):
    return render(request,"mediampesa/payment_success.html")

def payment_failed(request):
    return render(request,"mediampesa/payment_failed.html")

def payment_cancelled(request):
    return render(request,"mediampesa/payment_cancelled.html")
